# Generated by Django 5.0.2 on 2024-02-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='architecture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='cpus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memory',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='ram',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
