# Generated by Django 5.0.2 on 2024-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_virtualmachine_architecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualmachine',
            name='cpus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='memory',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='ram',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
