# Generated by Django 5.0.2 on 2024-02-17 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_virtualmachine_architecture_and_more'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deployment',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='jenkins_job',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='associated_site', to='automation.job'),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='virtual_machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.virtualmachine'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
