# Generated by Django 5.0.2 on 2024-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_alter_deployment_site_alter_site_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
