# Generated by Django 5.0.2 on 2024-02-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_site_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='jenkins_job',
        ),
        migrations.RemoveField(
            model_name='site',
            name='virtual_machine',
        ),
    ]
